name: Miami Open 211
url: http://miami.open.211.developer.adopta.agency/

author:
  name: 'Kin Lane'
  email: 'info@apievangelist.com'
markdown: kramdown

github_org: miami-open-211
github_repo: developer-portal-v1.2
